const products={
  'Diagnóstico Jurídico Empresarial':{question:'¿Dónde está hoy la mayor exposición jurídica de la empresa?',duration:'2 a 4 semanas',deliverables:['Informe ejecutivo de situación jurídica','Mapa priorizado de riesgos','Plan jurídico de 90 días','Sesión de dirección y recomendaciones'],limits:['No es auditoría legal exhaustiva','No incluye remediaciones no contratadas','Depende de la información entregada']},
  'Empresa Jurídicamente Organizada':{question:'¿La empresa puede crecer y decidir sin depender de memoria o acuerdos verbales?',duration:'6 a 10 semanas',deliverables:['Mapa societario y de poderes','Biblioteca contractual priorizada','Políticas esenciales','Calendario jurídico anual'],limits:['No incluye litigios ni saneamientos complejos','Trámites y tasas se dimensionan por separado']},
  'Marca, Software y Activos Intangibles Protegidos':{question:'¿La empresa controla jurídicamente los activos que está financiando?',duration:'3 a 8 semanas',deliverables:['Inventario y cadena de titularidad','Estrategia de protección','Cesiones, licencias o cláusulas prioritarias','Calendario de renovaciones'],limits:['No garantiza concesión registral','Litigios y oposiciones requieren alcance separado']},
  'Empresa Lista para Inversión':{question:'¿La empresa puede explicar su capital, gobierno, contratos y contingencias?',duration:'6 a 12 semanas',deliverables:['Informe de preparación','Plan de remediación','Cap table y matriz de gobierno','Índice de data room'],limits:['No incluye valoración financiera','Estructuración tributaria requiere especialista']},
  'Programa de Gobernanza de IA':{question:'¿La organización sabe dónde usa IA, qué datos intervienen y quién responde?',duration:'5 a 10 semanas',deliverables:['Inventario de casos de uso','Clasificación de riesgos','Política, roles y controles','Protocolo de proveedores e incidentes'],limits:['No es auditoría técnica de modelos','No certifica cumplimiento']},
  'Proyecto Regulado Estructurado':{question:'¿El proyecto es jurídicamente viable y qué condiciona su ejecución?',duration:'4 a 8 semanas',deliverables:['Concepto ejecutivo de viabilidad','Matriz de permisos y condicionantes','Arquitectura contractual','Hoja de ruta con responsables'],limits:['No incluye estudios técnicos','No garantiza permisos o financiación']},
  'Sistema Contractual Empresarial':{question:'¿La empresa sabe qué firma, quién aprueba y cuándo debe actuar?',duration:'6 a 10 semanas',deliverables:['Matriz contractual','Playbook de negociación','Biblioteca de modelos','Registro de obligaciones y renovaciones'],limits:['Revisión histórica masiva requiere dimensionamiento','Negociaciones extraordinarias se cotizan aparte']},
  'Programa de Protección de Datos y Consumidor':{question:'¿La empresa puede demostrar cómo recoge datos y atiende reclamos?',duration:'6 a 10 semanas',deliverables:['Mapa de datos y canales','Políticas, avisos y procedimientos','Matriz de proveedores','Registro de solicitudes e incidentes'],limits:['No incluye ciberseguridad técnica','Investigaciones y litigios se atienden por separado']}
};
const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');const f=tab.dataset.filter;document.querySelectorAll('.product-card').forEach(c=>c.classList.toggle('is-hidden',f!=='all'&&c.dataset.category!==f))}));
const modal=document.getElementById('product-modal');const modalContent=document.getElementById('modal-content');document.querySelectorAll('[data-product]').forEach(btn=>btn.addEventListener('click',()=>{const p=products[btn.dataset.product];modalContent.innerHTML=`<p class="eyebrow dark">FICHA EJECUTIVA</p><h2>${btn.dataset.product}</h2><p><strong>${p.question}</strong></p><div class="meta"><span>${p.duration}</span><span>Supervisión profesional</span><span>Alcance definido</span></div><h3>Entregables principales</h3><ul>${p.deliverables.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Límites</h3><ul>${p.limits.map(x=>`<li>${x}</li>`).join('')}</ul><a class="btn btn-dark" href="#contacto" onclick="document.getElementById('product-modal').close()">Solicitar propuesta</a>`;modal.showModal()}));document.querySelectorAll('.modal-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
const routeMap={empresa:'Diagnóstico Jurídico Empresarial',ia:'Programa de Gobernanza de IA',socios:'Empresa Lista para Inversión',intangibles:'Marca, Software y Activos Intangibles Protegidos',regulado:'Proyecto Regulado Estructurado',operacion:'Sistema Contractual Empresarial'};document.querySelectorAll('.need-card').forEach(card=>card.addEventListener('click',()=>{document.querySelector(`[data-product="${routeMap[card.dataset.route]}"]`)?.click()}));
const form=document.getElementById('contact-form');form?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const subject=encodeURIComponent(`Solicitud Meridiano Legal: ${fd.get('need')}`);const body=encodeURIComponent(`Nombre: ${fd.get('name')}\nEmpresa: ${fd.get('company')}\nCorreo: ${fd.get('email')}\nNecesidad: ${fd.get('need')}\n\nContexto general:\n${fd.get('message')}`);form.querySelector('.form-status').textContent='Solicitud preparada. Se abrirá su aplicación de correo.';window.location.href=`mailto:contacto@meridianolegal.co?subject=${subject}&body=${body}`});
document.getElementById('year').textContent=new Date().getFullYear();
