const users={
 'cliente@empresa-demo.com':{password:'Cliente2026!',name:'Laura Gómez',role:'Cliente demo',initials:'LG'},
 'abogado@meridianolegal.local':{password:'Abogado2026!',name:'Mariana Torres',role:'Abogada responsable',initials:'MT'},
 'admin@meridianolegal.local':{password:'Meridiano2026!',name:'Agustín Rendón',role:'Socio director',initials:'AR'}
};
const titles={dashboard:'Resumen',tickets:'Solicitudes',expedientes:'Expedientes',documentos:'Documentos guiados',archivos:'Archivos',obligaciones:'Obligaciones',calendario:'Calendario',riesgos:'Riesgos',analitica:'Analítica'};
const loginView=document.getElementById('login-view'),portalView=document.getElementById('portal-view'),loginForm=document.getElementById('login-form');
document.querySelectorAll('.credential-card').forEach(card=>card.addEventListener('click',()=>{document.getElementById('login-email').value=card.dataset.email;document.getElementById('login-password').value=card.dataset.password;document.getElementById('login-email').focus()}));
function openPanel(view){const button=document.querySelector(`.portal-nav[data-view="${view}"]`);if(!button)return;document.querySelectorAll('.portal-nav').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('.portal-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===view));document.getElementById('view-title').textContent=titles[view];history.replaceState(null,'',`#${view}`)}
function enterPortal(email){const u=users[email];sessionStorage.setItem('meridiano-demo-user',email);document.getElementById('user-name').textContent=u.name;document.getElementById('user-role').textContent=u.role;document.getElementById('avatar').textContent=u.initials;loginView.classList.add('hidden');portalView.classList.remove('hidden');const requested=location.hash.slice(1);if(titles[requested])openPanel(requested)}
loginForm.addEventListener('submit',e=>{e.preventDefault();const email=document.getElementById('login-email').value.trim().toLowerCase(),password=document.getElementById('login-password').value,status=document.getElementById('login-status');if(users[email]?.password===password){status.textContent='';enterPortal(email)}else status.textContent='Credenciales incorrectas. Use uno de los perfiles demostrativos.'});
const saved=sessionStorage.getItem('meridiano-demo-user');if(saved&&users[saved])enterPortal(saved);document.getElementById('logout').addEventListener('click',()=>{sessionStorage.removeItem('meridiano-demo-user');location.href='demo.html'});
document.querySelectorAll('.portal-nav').forEach(btn=>btn.addEventListener('click',()=>openPanel(btn.dataset.view)));
const tickets=[['TK-028','Revisión contrato de distribución','Contratos','Mariana T.','revision','04 ago'],['TK-027','Registro de marca nueva línea','Propiedad intelectual','Equipo PI','abierto','03 ago'],['TK-026','Acta de aprobación presupuesto','Societario','Mariana T.','espera','01 ago'],['TK-025','Matriz de permisos proyecto norte','Regulatorio','Carlos R.','revision','30 jul'],['TK-024','Respuesta a solicitud de datos','Datos','Mariana T.','cerrado','28 jul'],['TK-023','Actualización acuerdo de socios','Societario','Agustín R.','abierto','26 jul']];
function renderTickets(){const q=document.getElementById('ticket-search').value.toLowerCase(),f=document.getElementById('ticket-filter').value;document.getElementById('ticket-rows').innerHTML=tickets.filter(t=>(f==='all'||t[4]===f)&&t.join(' ').toLowerCase().includes(q)).map(t=>`<tr><td><strong>${t[0]}</strong></td><td>${t[1]}</td><td>${t[2]}</td><td>${t[3]}</td><td><span class="status-pill ${t[4]}">${{abierto:'ABIERTO',revision:'EN REVISIÓN',espera:'EN ESPERA',cerrado:'CERRADO'}[t[4]]}</span></td><td>${t[5]}</td></tr>`).join('')};document.getElementById('ticket-search').addEventListener('input',renderTickets);document.getElementById('ticket-filter').addEventListener('change',renderTickets);renderTickets();
const days=document.getElementById('calendar-days');const prev=4;let html='';for(let i=28;i<=31;i++)html+=`<div class="day muted">${i}</div>`;for(let i=1;i<=31;i++){const event={4:'Comité jurídico',12:'Hito regulatorio',19:'Renovación',27:'Cierre mensual'}[i];html+=`<div class="day ${event?'has-event':''}">${i}${event?`<i>${event}</i>`:''}</div>`}for(let i=1;i<=7-prev;i++)html+=`<div class="day muted">${i}</div>`;days.innerHTML=html;
document.querySelectorAll('.doc-template').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.doc-template').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.getElementById('doc-title').textContent=btn.dataset.doc;document.getElementById('doc-preview').classList.add('hidden')}));document.getElementById('generate-doc').addEventListener('click',()=>{const title=document.getElementById('doc-title').textContent,party=document.getElementById('doc-party').value||'[PARTE PRINCIPAL]',counter=document.getElementById('doc-counterparty').value||'[CONTRAPARTE]',object=document.getElementById('doc-object').value||'[OBJETO POR DEFINIR]',preview=document.getElementById('doc-preview');preview.innerHTML=`<p class="eyebrow dark">VISTA PREVIA FICTICIA</p><h3>${title}</h3><p>Entre <strong>${party}</strong> y <strong>${counter}</strong>, se estructura el presente instrumento respecto de: ${object}.</p><p>La versión final requeriría validación de capacidad, antecedentes, riesgos, anexos, obligaciones, responsabilidad, vigencia, terminación y demás condiciones aplicables.</p><small>Esta vista previa no constituye documento jurídico ni puede utilizarse para firma.</small>`;preview.classList.remove('hidden')});
const ticketModal=document.getElementById('ticket-modal');document.getElementById('new-ticket').addEventListener('click',()=>ticketModal.showModal());document.querySelectorAll('.modal-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.getElementById('ticket-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);tickets.unshift([`TK-${29+tickets.length}`,fd.get('subject'),fd.get('area'),'Por asignar','abierto','hoy']);renderTickets();e.target.querySelector('.form-status').textContent='Solicitud ficticia creada en esta sesión.';setTimeout(()=>{ticketModal.close();openPanel('tickets')},900)});
document.querySelector('.portal-panel[data-panel="archivos"] .btn')?.addEventListener('click',e=>{e.currentTarget.textContent='Carga deshabilitada en demo';e.currentTarget.disabled=true});
